id: PCA53D56D
initial_creation_type: ocr
source_metadata:
  volumes:
    efc4f1dea446475b8e829e77864e760c:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: གནོད་སྦྱིན་ནག་པོ་ཆེན་པོ་ལ་རིན་པོ་ཆེ་བསྟོད་པ།
      total_pages: 1902
      volume_number: 26
