id: PCA53D56D
initial_creation_type: ocr
source_metadata:
  volumes:
    942bc7158d744136897ce6105f1d2738:
      base_file: v047.txt
      image_group_id: I1PD95892
      title: གནོད་སྦྱིན་ནག་པོ་ཆེན་པོ་ལ་རིན་པོ་ཆེ་བསྟོད་པ།
      total_pages: 1464
      volume_number: 47
